import React, { createContext, useEffect, useMemo, useState } from 'react';

export const LanguageContext = createContext();

const translations = {
  vi: {
    common: {
      dashboard: 'Tổng quan',
      students: 'Sinh viên',
      classes: 'Lớp học',
      subjects: 'Môn học',
      classSubjects: 'Lớp-môn',
      scores: 'Điểm số',
      teachers: 'Giáo viên',
      terms: 'Học kỳ',
      rooms: 'Phòng học',
      schedule: 'Lịch học',
      enrollments: 'Đăng ký học',
      attendance: 'Điểm danh',
      logout: 'Đăng xuất',
      studentManagementSystem: 'Student Management System',
      loading: 'Đang tải...',
      noData: 'Không có dữ liệu',
      exportCsv: 'Xuất CSV',
      addNew: 'Thêm mới',
      save: 'Lưu',
      update: 'Cập nhật',
      cancel: 'Hủy',
      search: 'Tìm kiếm',
      details: 'Chi tiết',
      backToList: 'Quay lại danh sách',
      actions: 'Thao tác',
      status: 'Trạng thái',
      edit: 'Sửa',
      delete: 'Xóa',
      close: 'Đóng',
      yes: 'Có',
      no: 'Không',
      viewOnly: 'Chỉ xem',
      roleRestricted: 'Bạn không có quyền thực hiện thao tác này.'
    },
    login: {
      portal: 'SMS Portal',
      title: 'Student Management System',
      showcaseKicker: 'Student Management System',
      showcaseTitle: 'HỆ THỐNG\nQUẢN LÝ SINH VIÊN',
      description:
        'Hệ thống nội bộ hỗ trợ quản lý sinh viên, lớp học và quy trình học tập trên một giao diện tập trung.',
      access: 'Truy cập mọi lúc',
      flow: 'Đăng nhập nhanh gọn',
      secure: 'Phân quyền an toàn',
      welcome: 'Chào mừng trở lại',
      signIn: 'Đăng nhập',
      username: 'Tên đăng nhập',
      usernamePlaceholder: 'Nhập tên đăng nhập',
      password: 'Mật khẩu',
      passwordPlaceholder: 'Nhập mật khẩu',
      loginButton: 'Đăng nhập',
      loggingIn: 'Đang đăng nhập...',
      accountNotice: 'Tài khoản được cấp bởi nhà trường hoặc quản trị viên.',
      supportNotice: 'Nếu bạn chưa có tài khoản, vui lòng liên hệ phòng đào tạo hoặc admin hệ thống.'
    },
    navbar: {
      userRole: {
        student: 'Sinh viên',
        teacher: 'Giảng viên',
        admin: 'Quản trị viên'
      }
    },
    dashboard: {
      title: 'Tổng quan',
      welcome: 'Dữ liệu tổng hợp từ hệ thống quản lý sinh viên',
      totalStudents: 'Tổng sinh viên',
      totalClasses: 'Tổng lớp học',
      totalSubjects: 'Tổng môn học',
      averageScore: 'Điểm trung bình',
      recentActivity: 'Cập nhật gần đây',
      noRecentActivity: 'Chưa có hoạt động gần đây',
      quickActions: 'Tác vụ nhanh',
      addStudent: 'Thêm sinh viên',
      addClass: 'Thêm lớp học',
      addSubject: 'Thêm môn học',
      recordScore: 'Nhập điểm',
      latestStudents: 'Sinh viên mới cập nhật',
      dataSummary: 'Tóm tắt dữ liệu'
    },
    studentsPage: {
      title: 'Quản lý sinh viên',
      description: 'Tra cứu, cập nhật hồ sơ và nhập dữ liệu sinh viên theo lô từ một màn hình thống nhất.',
      addStudent: 'Thêm sinh viên',
      editStudent: 'Cập nhật sinh viên',
      searchPlaceholder: 'Tìm sinh viên theo tên hoặc email...',
      loadingStudents: 'Đang tải danh sách sinh viên...',
      noStudentsFound: 'Không tìm thấy sinh viên',
      confirmDelete: 'Bạn có chắc muốn xóa sinh viên này không?',
      confirmBulkDelete: 'Bạn có chắc muốn xóa {count} sinh viên đã chọn không?',
      bulkDelete: 'Xóa đã chọn',
      bulkDeleteEmpty: 'Vui lòng chọn ít nhất một sinh viên để xóa.',
      bulkDeletePartial: 'Đã xóa {count} sinh viên. Một số bản ghi không còn tồn tại.',
      selectedCount: 'Đã chọn: {count}',
      selectAll: 'Chọn tất cả sinh viên đang hiển thị',
      selectStudent: 'Chọn sinh viên',
      studentId: 'Mã sinh viên',
      name: 'Họ tên',
      email: 'Email',
      phone: 'Số điện thoại',
      class: 'Lớp',
      status: 'Trạng thái',
      actions: 'Thao tác',
      view: 'Xem',
      edit: 'Sửa',
      delete: 'Xóa',
      active: 'Đang học',
      inactive: 'Tạm dừng',
      graduated: 'Đã tốt nghiệp',
      suspended: 'Đình chỉ',
      importExcel: 'Nhập từ Excel',
      importDescription:
        'Dán dữ liệu đã copy từ Excel hoặc tải file CSV/TSV để thêm nhiều sinh viên cùng lúc.',
      importColumnsHelpLabel: 'Thứ tự cột hỗ trợ:',
      importColumnsHelp:
        'mã_sinh_viên | họ | tên | email | số_điện_thoại | ngày_sinh | giới_tính | địa_chỉ | tên_người_giám_hộ | số_điện_thoại_giám_hộ | mã_lớp | ngày_nhập_học | trạng_thái',
      importChooseFile: 'Chọn file',
      importOrUploadTitle: 'Hoặc tải file từ Excel',
      importSupportTypes: 'Hỗ trợ file .csv, .tsv hoặc .txt xuất từ Excel.',
      importSelectedFile: 'Đã chọn file:',
      importAction: 'Import dữ liệu',
      importPasteRequired: 'Vui lòng dán dữ liệu Excel trước khi import.',
      importParseFailed: 'Không đọc được dữ liệu. Hãy kiểm tra lại cột hoặc định dạng.',
      importFileReadFailed: 'Không đọc được file. Hãy thử lưu lại từ Excel dưới dạng CSV UTF-8 rồi tải lên lại.',
      importCreatedLabel: 'Đã tạo:',
      importErrorsLabel: 'Lỗi:',
      importRowLabel: 'Dòng',
      rowsPerPage: 'Số dòng/trang',
      previousPage: 'Trang trước',
      nextPage: 'Trang sau',
      pageIndicator: 'Trang {page}/{totalPages}',
      paginationSummary: 'Hiển thị {from}-{to} trên {total}',
      importPlaceholder:
        'mã_sinh_viên\thọ\ttên\temail\tsố_điện_thoại\tngày_sinh\tgiới_tính\tđịa_chỉ\ttên_người_giám_hộ\tsố_điện_thoại_giám_hộ\tmã_lớp\tngày_nhập_học\ttrạng_thái'
    },
    studentForm: {
      studentId: 'Mã sinh viên',
      firstName: 'Tên',
      lastName: 'Họ',
      email: 'Email',
      phone: 'Số điện thoại',
      dateOfBirth: 'Ngày sinh',
      gender: 'Giới tính',
      address: 'Địa chỉ',
      guardianName: 'Tên người giám hộ',
      guardianPhone: 'Số điện thoại người giám hộ',
      class: 'Lớp',
      enrollmentDate: 'Ngày nhập học',
      status: 'Trạng thái',
      saveStudent: 'Lưu sinh viên',
      updateStudent: 'Cập nhật sinh viên',
      saving: 'Đang lưu...',
      placeholderStudentId: 'Ví dụ: SV001',
      placeholderClassId: 'Mã lớp',
      requiredStudentId: 'Mã sinh viên là bắt buộc',
      requiredFirstName: 'Tên là bắt buộc',
      requiredLastName: 'Họ là bắt buộc',
      requiredEmail: 'Email là bắt buộc',
      requiredClass: 'Lớp là bắt buộc',
      male: 'Nam',
      female: 'Nữ',
      other: 'Khác',
      active: 'Đang học',
      inactive: 'Tạm dừng',
      graduated: 'Đã tốt nghiệp',
      suspended: 'Đình chỉ'
    },
    classesPage: {
      title: 'Quản lý lớp học',
      description: 'Theo dõi cấu trúc lớp học, niên khóa và sức chứa của từng lớp trong hệ thống.',
      addClass: 'Thêm lớp học',
      editClass: 'Cập nhật lớp học',
      searchPlaceholder: 'Tìm lớp theo tên hoặc niên khóa...',
      noClassesFound: 'Không tìm thấy lớp học',
      loadingClasses: 'Đang tải danh sách lớp học...',
      confirmDelete: 'Bạn có chắc muốn xóa lớp học này không?',
      name: 'Tên lớp',
      gradeLevel: 'Khối',
      academicYear: 'Niên khóa',
      capacity: 'Sức chứa',
      descriptionLabel: 'Mô tả',
      homeroomTeacher: 'Giáo viên chủ nhiệm'
    },
    subjectsPage: {
      title: 'Quản lý môn học',
      description: 'Chuẩn hóa danh mục môn học, mã môn và tín chỉ để dùng thống nhất trên toàn hệ thống.',
      addSubject: 'Thêm môn học',
      editSubject: 'Cập nhật môn học',
      searchPlaceholder: 'Tìm môn học theo tên hoặc mã môn...',
      noSubjectsFound: 'Không tìm thấy môn học',
      loadingSubjects: 'Đang tải danh sách môn học...',
      confirmDelete: 'Bạn có chắc muốn xóa môn học này không?',
      name: 'Tên môn',
      code: 'Mã môn',
      credits: 'Số tín chỉ',
      descriptionLabel: 'Mô tả',
      active: 'Đang mở',
      inactive: 'Tạm khóa'
    },
    classSubjectsPage: {
      title: 'Quản lý lớp-môn',
      description: 'Tạo và quản lý mã lớp-môn để dùng cho đăng ký học, lịch học và điểm danh.',
      addClassSubject: 'Thêm lớp-môn',
      editClassSubject: 'Cập nhật lớp-môn',
      searchPlaceholder: 'Tìm theo lớp, môn, học kỳ hoặc giáo viên...',
      confirmDelete: 'Bạn có chắc muốn xóa lớp-môn này không?',
      classSubjectId: 'Mã lớp-môn',
      classLabel: 'Lớp',
      subjectLabel: 'Môn học',
      termLabel: 'Học kỳ',
      teacherLabel: 'Giáo viên',
      assignedAt: 'Ngày phân công',
      isRequired: 'Bắt buộc',
      required: 'Bắt buộc',
      optional: 'Tự chọn'
    },
    scoresPage: {
      title: 'Quản lý điểm số',
      description: 'Quản lý các đầu điểm theo mã đăng ký học, kèm loại điểm, trọng số và ngày kiểm tra.',
      addScore: 'Thêm điểm',
      editScore: 'Cập nhật điểm',
      loadingScores: 'Đang tải danh sách điểm...',
      noScoresFound: 'Không có dữ liệu điểm',
      confirmDelete: 'Bạn có chắc muốn xóa điểm này không?',
      enrollmentId: 'Mã đăng ký học',
      scoreType: 'Loại điểm',
      score: 'Điểm',
      maxScore: 'Điểm tối đa',
      weight: 'Trọng số',
      grade: 'Xếp loại',
      examDate: 'Ngày kiểm tra',
      remarks: 'Ghi chú',
      searchPlaceholder: 'Tìm theo mã đăng ký học hoặc loại điểm...',
      quiz: 'Bài kiểm tra',
      assignment: 'Bài tập',
      midterm: 'Giữa kỳ',
      final: 'Cuối kỳ',
      practice: 'Thực hành'
    },
    teachersPage: {
      title: 'Quản lý giáo viên',
      description: 'Tra cứu, cập nhật hồ sơ giáo viên theo một màn hình thống nhất.',
      addTeacher: 'Thêm giáo viên',
      editTeacher: 'Cập nhật giáo viên',
      searchPlaceholder: 'Tìm giáo viên theo mã, tên, email...',
      loadingTeachers: 'Đang tải danh sách giáo viên...',
      confirmDelete: 'Bạn có chắc muốn xóa giáo viên này không?',
      teacherCode: 'Mã giáo viên',
      name: 'Họ tên',
      email: 'Email',
      phone: 'Số điện thoại',
      qualification: 'Trình độ',
      hireDate: 'Ngày vào làm'
    },
    teacherForm: {
      teacherCode: 'Mã giáo viên',
      lastName: 'Họ',
      firstName: 'Tên',
      email: 'Email',
      phone: 'Số điện thoại',
      qualification: 'Trình độ',
      hireDate: 'Ngày vào làm',
      saveTeacher: 'Lưu giáo viên',
      updateTeacher: 'Cập nhật giáo viên',
      saving: 'Đang lưu...',
      requiredTeacherCode: 'Mã giáo viên là bắt buộc',
      requiredLastName: 'Họ là bắt buộc',
      requiredFirstName: 'Tên là bắt buộc',
      requiredEmail: 'Email là bắt buộc'
    },
    termsPage: {
      title: 'Học kỳ',
      description: 'Quản lý học kỳ/năm học phục vụ phân lịch và đăng ký học.',
      addTerm: 'Thêm học kỳ',
      editTerm: 'Cập nhật học kỳ',
      searchPlaceholder: 'Tìm theo tên, năm học, trạng thái...',
      loadingTerms: 'Đang tải danh sách học kỳ...',
      confirmDelete: 'Bạn có chắc muốn xóa học kỳ này không?',
      name: 'Tên',
      academicYear: 'Năm học',
      semesterNo: 'Học kỳ',
      startDate: 'Bắt đầu',
      endDate: 'Kết thúc',
      status: 'Trạng thái',
      statusLabels: {
        du_kien: 'Dự kiến',
        dang_dien_ra: 'Đang diễn ra',
        da_ket_thuc: 'Đã kết thúc'
      }
    },
    termForm: {
      name: 'Tên học kỳ',
      academicYear: 'Năm học',
      semesterNo: 'Số học kỳ',
      startDate: 'Ngày bắt đầu',
      endDate: 'Ngày kết thúc',
      status: 'Trạng thái',
      saveTerm: 'Lưu học kỳ',
      updateTerm: 'Cập nhật học kỳ',
      saving: 'Đang lưu...',
      requiredName: 'Tên học kỳ là bắt buộc',
      requiredAcademicYear: 'Năm học là bắt buộc',
      requiredStartDate: 'Ngày bắt đầu là bắt buộc',
      requiredEndDate: 'Ngày kết thúc là bắt buộc'
    },
    roomsPage: {
      title: 'Phòng học',
      description: 'Quản lý phòng học/phòng lab dùng cho lịch học và điểm danh.',
      addRoom: 'Thêm phòng',
      editRoom: 'Cập nhật phòng học',
      searchPlaceholder: 'Tìm theo mã phòng, tòa nhà...',
      loadingRooms: 'Đang tải danh sách phòng học...',
      confirmDelete: 'Bạn có chắc muốn xóa phòng học này không?',
      roomCode: 'Mã phòng',
      building: 'Tòa nhà',
      floorNo: 'Tầng',
      capacity: 'Sức chứa',
      roomType: 'Loại',
      roomTypeLabels: {
        classroom: 'Phòng học',
        lab: 'Phòng lab'
      }
    },
    roomForm: {
      roomCode: 'Mã phòng',
      building: 'Tòa nhà',
      floorNo: 'Tầng',
      capacity: 'Sức chứa',
      roomType: 'Loại phòng',
      saveRoom: 'Lưu phòng học',
      updateRoom: 'Cập nhật phòng học',
      saving: 'Đang lưu...',
      requiredRoomCode: 'Mã phòng là bắt buộc'
    },
    schedulePage: {
      title: 'Lịch học',
      description: 'Quản lý lịch học theo lớp môn học, giáo viên và phòng học.',
      addSchedule: 'Thêm lịch',
      editSchedule: 'Cập nhật lịch học',
      searchPlaceholder: 'Tìm theo class_subject_id, teacher_id, thứ...',
      loadingSchedules: 'Đang tải danh sách lịch học...',
      confirmDelete: 'Bạn có chắc muốn xóa lịch học này không?',
      id: 'ID',
      classSubject: 'Lớp môn học',
      teacher: 'Giáo viên',
      room: 'Phòng',
      dayOfWeek: 'Thứ',
      startTime: 'Bắt đầu',
      endTime: 'Kết thúc',
      active: 'Kích hoạt',
      days: {
        Monday: 'Thứ 2',
        Tuesday: 'Thứ 3',
        Wednesday: 'Thứ 4',
        Thursday: 'Thứ 5',
        Friday: 'Thứ 6',
        Saturday: 'Thứ 7',
        Sunday: 'Chủ nhật'
      }
    },
    scheduleForm: {
      classSubjectId: 'Mã lớp-môn',
      teacherId: 'Mã giáo viên',
      roomId: 'Mã phòng',
      dayOfWeek: 'Thứ',
      startTime: 'Giờ bắt đầu',
      endTime: 'Giờ kết thúc',
      lessonNo: 'Tiết',
      isActive: 'Kích hoạt',
      saveSchedule: 'Lưu lịch học',
      updateSchedule: 'Cập nhật lịch học',
      saving: 'Đang lưu...',
      requiredClassSubjectId: 'class_subject_id là bắt buộc',
      requiredTeacherId: 'teacher_id là bắt buộc',
      requiredStartTime: 'Giờ bắt đầu là bắt buộc',
      requiredEndTime: 'Giờ kết thúc là bắt buộc'
    },
    enrollmentsPage: {
      title: 'Đăng ký học',
      description: 'Quản lý đăng ký học theo sinh viên và lớp môn học.',
      addEnrollment: 'Thêm đăng ký',
      editEnrollment: 'Cập nhật đăng ký',
      searchPlaceholder: 'Tìm theo student_id, class_subject_id, trạng thái...',
      loadingEnrollments: 'Đang tải danh sách đăng ký học...',
      confirmDelete: 'Bạn có chắc muốn xóa đăng ký học này không?',
      id: 'ID',
      student: 'Sinh viên',
      classSubject: 'Lớp môn học',
      status: 'Trạng thái',
      notes: 'Ghi chú',
      statusLabels: {
        enrolled: 'Đang học',
        dropped: 'Rút môn',
        completed: 'Hoàn thành',
        failed: 'Không đạt'
      }
    },
    enrollmentForm: {
      studentId: 'Mã sinh viên',
      classSubjectId: 'Mã lớp-môn',
      status: 'Trạng thái',
      notes: 'Ghi chú',
      saveEnrollment: 'Lưu đăng ký',
      updateEnrollment: 'Cập nhật đăng ký',
      saving: 'Đang lưu...',
      requiredStudentId: 'student_id là bắt buộc',
      requiredClassSubjectId: 'class_subject_id là bắt buộc'
    },
    attendancePage: {
      title: 'Điểm danh',
      description: 'Ghi nhận trạng thái điểm danh theo lịch học và đăng ký học.',
      addAttendance: 'Thêm điểm danh',
      editAttendance: 'Cập nhật điểm danh',
      searchPlaceholder: 'Tìm theo enrollment_id, schedule_id, ngày...',
      loadingAttendance: 'Đang tải danh sách điểm danh...',
      confirmDelete: 'Bạn có chắc muốn xóa điểm danh này không?',
      id: 'ID',
      enrollment: 'Đăng ký',
      schedule: 'Lịch học',
      classSubject: 'Lớp môn học',
      date: 'Ngày',
      status: 'Trạng thái',
      notes: 'Ghi chú',
      statusLabels: {
        Present: 'Có mặt',
        Absent: 'Vắng',
        Late: 'Trễ',
        Excused: 'Có phép'
      }
    },
    attendanceForm: {
      enrollmentId: 'Mã đăng ký',
      scheduleId: 'Mã lịch học',
      classSubjectId: 'Mã lớp-môn',
      date: 'Ngày điểm danh',
      status: 'Trạng thái',
      notes: 'Ghi chú',
      saveAttendance: 'Lưu điểm danh',
      updateAttendance: 'Cập nhật điểm danh',
      saving: 'Đang lưu...',
      requiredEnrollmentId: 'enrollment_id là bắt buộc',
      requiredScheduleId: 'class_schedule_id là bắt buộc',
      requiredClassSubjectId: 'class_subject_id là bắt buộc',
      requiredDate: 'Ngày điểm danh là bắt buộc'
    },
    studentDetailPage: {
      title: 'Chi tiết sinh viên',
      summary: 'Tổng quan hồ sơ',
      personalInfo: 'Thông tin cá nhân',
      enrollments: 'Đăng ký học',
      scores: 'Điểm số',
      classInfo: 'Lớp hiện tại',
      enrollmentDate: 'Ngày nhập học',
      averageScore: 'Điểm trung bình',
      studentCode: 'Mã sinh viên',
      fullName: 'Họ tên',
      email: 'Email',
      phone: 'Số điện thoại',
      gender: 'Giới tính',
      dateOfBirth: 'Ngày sinh',
      address: 'Địa chỉ',
      guardianName: 'Tên người giám hộ',
      guardianPhone: 'Số điện thoại người giám hộ',
      status: 'Trạng thái',
      enrollmentId: 'Mã đăng ký',
      classSubjectId: 'Mã lớp-môn',
      scoreType: 'Loại điểm',
      score: 'Điểm',
      examDate: 'Ngày kiểm tra',
      emptyEnrollments: 'Chưa có đăng ký học',
      emptyScores: 'Chưa có điểm số',
      notFound: 'Không tìm thấy sinh viên',
      scoreRecordsSuffix: 'đầu điểm'
    },
    classDetailPage: {
      title: 'Chi tiết lớp học',
      overview: 'Tổng quan lớp',
      studentCount: 'Số sinh viên',
      classSubjects: 'Môn học theo lớp',
      students: 'Danh sách sinh viên',
      gradeLevel: 'Khối',
      academicYear: 'Niên khóa',
      capacity: 'Sức chứa',
      description: 'Mô tả',
      classSubjectId: 'Mã lớp-môn',
      subjectId: 'Mã môn',
      termId: 'Mã học kỳ',
      studentCode: 'Mã sinh viên',
      fullName: 'Họ tên',
      email: 'Email',
      notFound: 'Không tìm thấy lớp học',
      activeRecords: 'hồ sơ đang hoạt động',
      subjectAssignments: 'phân công lớp-môn'
    },
    subjectDetailPage: {
      title: 'Chi tiết môn học',
      summary: 'Tổng quan môn học',
      subjectCode: 'Mã môn',
      credits: 'Tín chỉ',
      averageScore: 'Điểm trung bình',
      scoreCount: 'Số đầu điểm',
      description: 'Mô tả',
      classSubjects: 'Lớp đang học môn này',
      scores: 'Điểm gần nhất',
      classSubjectId: 'Mã lớp-môn',
      classId: 'Mã lớp',
      termId: 'Mã học kỳ',
      scoreType: 'Loại điểm',
      score: 'Điểm',
      notFound: 'Không tìm thấy môn học',
      activeMappings: 'lớp đang áp dụng'
    },
    scoreDetailPage: {
      title: 'Chi tiết điểm số',
      summary: 'Tổng quan đầu điểm',
      scoreType: 'Loại điểm',
      score: 'Điểm',
      maxScore: 'Điểm tối đa',
      weight: 'Trọng số',
      grade: 'Xếp loại',
      examDate: 'Ngày kiểm tra',
      remarks: 'Ghi chú',
      enrollment: 'Đăng ký học',
      enrollmentId: 'Mã đăng ký',
      student: 'Sinh viên',
      studentId: 'Mã sinh viên',
      classSubjectId: 'Mã lớp-môn',
      notFound: 'Không tìm thấy đầu điểm'
    }
  },
  en: {
    common: {
      dashboard: 'Dashboard',
      students: 'Students',
      classes: 'Classes',
      subjects: 'Subjects',
      classSubjects: 'Class subjects',
      scores: 'Scores',
      teachers: 'Teachers',
      terms: 'Academic terms',
      rooms: 'Rooms',
      schedule: 'Schedule',
      enrollments: 'Enrollments',
      attendance: 'Attendance',
      logout: 'Logout',
      studentManagementSystem: 'Student Management System',
      loading: 'Loading...',
      noData: 'No data',
      exportCsv: 'Export CSV',
      addNew: 'Add new',
      save: 'Save',
      update: 'Update',
      cancel: 'Cancel',
      search: 'Search',
      details: 'Details',
      backToList: 'Back to list',
      actions: 'Actions',
      status: 'Status',
      edit: 'Edit',
      delete: 'Delete',
      close: 'Close',
      yes: 'Yes',
      no: 'No',
      viewOnly: 'View only',
      roleRestricted: 'You do not have permission to perform this action.'
    },
    login: {
      portal: 'SMS Portal',
      title: 'Student Management System',
      showcaseKicker: 'Student Management System',
      showcaseTitle: 'STUDENT\nMANAGEMENT\nSYSTEM',
      description:
        'An internal portal for managing students, classes, and academic workflows in one place.',
      access: 'Access anywhere',
      flow: 'Simple login flow',
      secure: 'Role-based access',
      welcome: 'Welcome back',
      signIn: 'Sign in',
      username: 'Username',
      usernamePlaceholder: 'Enter your username',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      loginButton: 'Login',
      loggingIn: 'Logging in...',
      accountNotice: 'Accounts are issued by the school or system administrator.',
      supportNotice: 'If you do not have an account yet, please contact your administrator.'
    },
    navbar: {
      userRole: {
        student: 'Student',
        teacher: 'Teacher',
        admin: 'Admin'
      }
    },
    dashboard: {
      title: 'Dashboard',
      welcome: 'Live summary from the student management system',
      totalStudents: 'Total students',
      totalClasses: 'Total classes',
      totalSubjects: 'Total subjects',
      averageScore: 'Average score',
      recentActivity: 'Recent activity',
      noRecentActivity: 'No recent activity to display',
      quickActions: 'Quick actions',
      addStudent: 'Add student',
      addClass: 'Add class',
      addSubject: 'Add subject',
      recordScore: 'Record score',
      latestStudents: 'Recently updated students',
      dataSummary: 'Data summary'
    },
    studentsPage: {
      title: 'Student Management',
      description: 'Search, update, and bulk-import students in one unified view.',
      addStudent: 'Add student',
      editStudent: 'Edit student',
      searchPlaceholder: 'Search students by name or email...',
      loadingStudents: 'Loading students...',
      noStudentsFound: 'No students found',
      confirmDelete: 'Are you sure you want to delete this student?',
      confirmBulkDelete: 'Are you sure you want to delete {count} selected students?',
      bulkDelete: 'Delete selected',
      bulkDeleteEmpty: 'Please select at least one student to delete.',
      bulkDeletePartial: 'Deleted {count} students. Some records no longer existed.',
      selectedCount: 'Selected: {count}',
      selectAll: 'Select all visible students',
      selectStudent: 'Select student',
      studentId: 'Student code',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      class: 'Class',
      status: 'Status',
      actions: 'Actions',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
      active: 'Active',
      inactive: 'Inactive',
      graduated: 'Graduated',
      suspended: 'Suspended',
      importExcel: 'Import from Excel',
      importDescription:
        'Paste data copied from Excel or upload a CSV/TSV file to add multiple students at once.',
      importColumnsHelpLabel: 'Supported columns order:',
      importColumnsHelp:
        'student_code | last_name | first_name | email | phone | date_of_birth | gender | address | guardian_name | guardian_phone | class_id | enrollment_date | status',
      importChooseFile: 'Choose file',
      importOrUploadTitle: 'Or upload from Excel',
      importSupportTypes: 'Supports .csv, .tsv, or .txt exported from Excel.',
      importSelectedFile: 'Selected file:',
      importAction: 'Import data',
      importPasteRequired: 'Please paste Excel data before importing.',
      importParseFailed: 'Unable to parse data. Please check columns or formatting.',
      importFileReadFailed: 'Unable to read file. Try exporting CSV as UTF-8 from Excel and upload again.',
      importCreatedLabel: 'Created:',
      importErrorsLabel: 'Errors:',
      importRowLabel: 'Row',
      rowsPerPage: 'Rows per page',
      previousPage: 'Previous',
      nextPage: 'Next',
      pageIndicator: 'Page {page} of {totalPages}',
      paginationSummary: 'Showing {from}-{to} of {total}',
      importPlaceholder:
        'student_code\tlast_name\tfirst_name\temail\tphone\tdate_of_birth\tgender\taddress\tguardian_name\tguardian_phone\tclass_id\tenrollment_date\tstatus'
    },
    studentForm: {
      studentId: 'Student code',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      dateOfBirth: 'Date of birth',
      gender: 'Gender',
      address: 'Address',
      guardianName: 'Guardian name',
      guardianPhone: 'Guardian phone',
      class: 'Class',
      enrollmentDate: 'Enrollment date',
      status: 'Status',
      saveStudent: 'Save student',
      updateStudent: 'Update student',
      saving: 'Saving...',
      placeholderStudentId: 'e.g. SV001',
      placeholderClassId: 'Class ID',
      requiredStudentId: 'Student code is required',
      requiredFirstName: 'First name is required',
      requiredLastName: 'Last name is required',
      requiredEmail: 'Email is required',
      requiredClass: 'Class is required',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      active: 'Active',
      inactive: 'Inactive',
      graduated: 'Graduated',
      suspended: 'Suspended'
    },
    classesPage: {
      title: 'Class Management',
      description: 'Track class structure, academic year, and capacity across the system.',
      addClass: 'Add class',
      editClass: 'Edit class',
      searchPlaceholder: 'Search classes by name or academic year...',
      noClassesFound: 'No classes found',
      loadingClasses: 'Loading classes...',
      confirmDelete: 'Are you sure you want to delete this class?',
      name: 'Class name',
      gradeLevel: 'Grade level',
      academicYear: 'Academic year',
      capacity: 'Capacity',
      descriptionLabel: 'Description',
      homeroomTeacher: 'Homeroom teacher'
    },
    subjectsPage: {
      title: 'Subject Management',
      description: 'Standardize subjects, codes, and credits for consistent usage across the system.',
      addSubject: 'Add subject',
      editSubject: 'Edit subject',
      searchPlaceholder: 'Search subjects by name or code...',
      noSubjectsFound: 'No subjects found',
      loadingSubjects: 'Loading subjects...',
      confirmDelete: 'Are you sure you want to delete this subject?',
      name: 'Subject name',
      code: 'Code',
      credits: 'Credits',
      descriptionLabel: 'Description',
      active: 'Active',
      inactive: 'Inactive'
    },
    classSubjectsPage: {
      title: 'Class Subject Management',
      description: 'Create and manage class-subject mappings for enrollments, schedules, and attendance.',
      addClassSubject: 'Add class subject',
      editClassSubject: 'Edit class subject',
      searchPlaceholder: 'Search by class, subject, term, or teacher...',
      confirmDelete: 'Are you sure you want to delete this class subject?',
      classSubjectId: 'Class-subject ID',
      classLabel: 'Class',
      subjectLabel: 'Subject',
      termLabel: 'Term',
      teacherLabel: 'Teacher',
      assignedAt: 'Assigned date',
      isRequired: 'Required',
      required: 'Required',
      optional: 'Optional'
    },
    scoresPage: {
      title: 'Score Management',
      description: 'Manage score records by enrollment, score type, weight, and exam date.',
      addScore: 'Add score',
      editScore: 'Edit score',
      loadingScores: 'Loading scores...',
      noScoresFound: 'No scores found',
      confirmDelete: 'Are you sure you want to delete this score?',
      enrollmentId: 'Enrollment ID',
      scoreType: 'Score type',
      score: 'Score',
      maxScore: 'Max score',
      weight: 'Weight',
      grade: 'Grade',
      examDate: 'Exam date',
      remarks: 'Remarks',
      searchPlaceholder: 'Search by enrollment ID or score type...',
      quiz: 'Quiz',
      assignment: 'Assignment',
      midterm: 'Midterm',
      final: 'Final',
      practice: 'Practice'
    },
    teachersPage: {
      title: 'Teacher Management',
      description: 'Search and update teacher profiles in one place.',
      addTeacher: 'Add teacher',
      editTeacher: 'Edit teacher',
      searchPlaceholder: 'Search by code, name, email...',
      loadingTeachers: 'Loading teachers...',
      confirmDelete: 'Are you sure you want to delete this teacher?',
      teacherCode: 'Teacher code',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      qualification: 'Qualification',
      hireDate: 'Hire date'
    },
    teacherForm: {
      teacherCode: 'Teacher code',
      lastName: 'Last name',
      firstName: 'First name',
      email: 'Email',
      phone: 'Phone',
      qualification: 'Qualification',
      hireDate: 'Hire date',
      saveTeacher: 'Save teacher',
      updateTeacher: 'Update teacher',
      saving: 'Saving...',
      requiredTeacherCode: 'Teacher code is required',
      requiredLastName: 'Last name is required',
      requiredFirstName: 'First name is required',
      requiredEmail: 'Email is required'
    },
    termsPage: {
      title: 'Academic terms',
      description: 'Manage academic terms and school years for scheduling and enrollments.',
      addTerm: 'Add term',
      editTerm: 'Edit term',
      searchPlaceholder: 'Search by name, year, status...',
      loadingTerms: 'Loading terms...',
      confirmDelete: 'Are you sure you want to delete this term?',
      name: 'Name',
      academicYear: 'Academic year',
      semesterNo: 'Semester',
      startDate: 'Start',
      endDate: 'End',
      status: 'Status',
      statusLabels: {
        du_kien: 'Planned',
        dang_dien_ra: 'Ongoing',
        da_ket_thuc: 'Finished'
      }
    },
    termForm: {
      name: 'Term name',
      academicYear: 'Academic year',
      semesterNo: 'Semester number',
      startDate: 'Start date',
      endDate: 'End date',
      status: 'Status',
      saveTerm: 'Save term',
      updateTerm: 'Update term',
      saving: 'Saving...',
      requiredName: 'Term name is required',
      requiredAcademicYear: 'Academic year is required',
      requiredStartDate: 'Start date is required',
      requiredEndDate: 'End date is required'
    },
    roomsPage: {
      title: 'Rooms',
      description: 'Manage classrooms and labs for schedules and attendance.',
      addRoom: 'Add room',
      editRoom: 'Edit room',
      searchPlaceholder: 'Search by room code, building...',
      loadingRooms: 'Loading rooms...',
      confirmDelete: 'Are you sure you want to delete this room?',
      roomCode: 'Room code',
      building: 'Building',
      floorNo: 'Floor',
      capacity: 'Capacity',
      roomType: 'Type',
      roomTypeLabels: {
        classroom: 'Classroom',
        lab: 'Lab'
      }
    },
    roomForm: {
      roomCode: 'Room code',
      building: 'Building',
      floorNo: 'Floor',
      capacity: 'Capacity',
      roomType: 'Room type',
      saveRoom: 'Save room',
      updateRoom: 'Update room',
      saving: 'Saving...',
      requiredRoomCode: 'Room code is required'
    },
    schedulePage: {
      title: 'Schedule',
      description: 'Manage schedules by class subject, teacher, and room.',
      addSchedule: 'Add schedule',
      editSchedule: 'Edit schedule',
      searchPlaceholder: 'Search by class_subject_id, teacher_id, day...',
      loadingSchedules: 'Loading schedules...',
      confirmDelete: 'Are you sure you want to delete this schedule?',
      id: 'ID',
      classSubject: 'Class subject',
      teacher: 'Teacher',
      room: 'Room',
      dayOfWeek: 'Day',
      startTime: 'Start',
      endTime: 'End',
      active: 'Active',
      days: {
        Monday: 'Monday',
        Tuesday: 'Tuesday',
        Wednesday: 'Wednesday',
        Thursday: 'Thursday',
        Friday: 'Friday',
        Saturday: 'Saturday',
        Sunday: 'Sunday'
      }
    },
    scheduleForm: {
      classSubjectId: 'Class Subject ID',
      teacherId: 'Teacher ID',
      roomId: 'Room ID',
      dayOfWeek: 'Day',
      startTime: 'Start time',
      endTime: 'End time',
      lessonNo: 'Lesson',
      isActive: 'Active',
      saveSchedule: 'Save schedule',
      updateSchedule: 'Update schedule',
      saving: 'Saving...',
      requiredClassSubjectId: 'class_subject_id is required',
      requiredTeacherId: 'teacher_id is required',
      requiredStartTime: 'Start time is required',
      requiredEndTime: 'End time is required'
    },
    enrollmentsPage: {
      title: 'Enrollments',
      description: 'Manage enrollments by student and class subject.',
      addEnrollment: 'Add enrollment',
      editEnrollment: 'Edit enrollment',
      searchPlaceholder: 'Search by student_id, class_subject_id, status...',
      loadingEnrollments: 'Loading enrollments...',
      confirmDelete: 'Are you sure you want to delete this enrollment?',
      id: 'ID',
      student: 'Student',
      classSubject: 'Class subject',
      status: 'Status',
      notes: 'Notes',
      statusLabels: {
        enrolled: 'Enrolled',
        dropped: 'Dropped',
        completed: 'Completed',
        failed: 'Failed'
      }
    },
    enrollmentForm: {
      studentId: 'Student ID',
      classSubjectId: 'Class Subject ID',
      status: 'Status',
      notes: 'Notes',
      saveEnrollment: 'Save enrollment',
      updateEnrollment: 'Update enrollment',
      saving: 'Saving...',
      requiredStudentId: 'student_id is required',
      requiredClassSubjectId: 'class_subject_id is required'
    },
    attendancePage: {
      title: 'Attendance',
      description: 'Track attendance status by schedule and enrollment.',
      addAttendance: 'Add attendance',
      editAttendance: 'Edit attendance',
      searchPlaceholder: 'Search by enrollment_id, schedule_id, date...',
      loadingAttendance: 'Loading attendance...',
      confirmDelete: 'Are you sure you want to delete this record?',
      id: 'ID',
      enrollment: 'Enrollment',
      schedule: 'Schedule',
      classSubject: 'Class subject',
      date: 'Date',
      status: 'Status',
      notes: 'Notes',
      statusLabels: {
        Present: 'Present',
        Absent: 'Absent',
        Late: 'Late',
        Excused: 'Excused'
      }
    },
    attendanceForm: {
      enrollmentId: 'Enrollment ID',
      scheduleId: 'Schedule ID',
      classSubjectId: 'Class Subject ID',
      date: 'Attendance date',
      status: 'Status',
      notes: 'Notes',
      saveAttendance: 'Save attendance',
      updateAttendance: 'Update attendance',
      saving: 'Saving...',
      requiredEnrollmentId: 'enrollment_id is required',
      requiredScheduleId: 'class_schedule_id is required',
      requiredClassSubjectId: 'class_subject_id is required',
      requiredDate: 'Attendance date is required'
    },
    studentDetailPage: {
      title: 'Student details',
      summary: 'Profile summary',
      personalInfo: 'Personal information',
      enrollments: 'Enrollments',
      scores: 'Scores',
      classInfo: 'Current class',
      enrollmentDate: 'Enrollment date',
      averageScore: 'Average score',
      studentCode: 'Student code',
      fullName: 'Full name',
      email: 'Email',
      phone: 'Phone',
      gender: 'Gender',
      dateOfBirth: 'Date of birth',
      address: 'Address',
      guardianName: 'Guardian name',
      guardianPhone: 'Guardian phone',
      status: 'Status',
      enrollmentId: 'Enrollment ID',
      classSubjectId: 'Class-subject ID',
      scoreType: 'Score type',
      score: 'Score',
      examDate: 'Exam date',
      emptyEnrollments: 'No enrollments yet',
      emptyScores: 'No scores yet',
      notFound: 'Student not found',
      scoreRecordsSuffix: 'records'
    },
    classDetailPage: {
      title: 'Class details',
      overview: 'Class overview',
      studentCount: 'Students',
      classSubjects: 'Assigned subjects',
      students: 'Students',
      gradeLevel: 'Grade level',
      academicYear: 'Academic year',
      capacity: 'Capacity',
      description: 'Description',
      classSubjectId: 'Class-subject ID',
      subjectId: 'Subject ID',
      termId: 'Term ID',
      studentCode: 'Student code',
      fullName: 'Full name',
      email: 'Email',
      notFound: 'Class not found',
      activeRecords: 'active records',
      subjectAssignments: 'subject assignments'
    },
    subjectDetailPage: {
      title: 'Subject details',
      summary: 'Subject overview',
      subjectCode: 'Subject code',
      credits: 'Credits',
      averageScore: 'Average score',
      scoreCount: 'Score count',
      description: 'Description',
      classSubjects: 'Classes using this subject',
      scores: 'Latest scores',
      classSubjectId: 'Class-subject ID',
      classId: 'Class ID',
      termId: 'Term ID',
      scoreType: 'Score type',
      score: 'Score',
      notFound: 'Subject not found',
      activeMappings: 'active class mappings'
    },
    scoreDetailPage: {
      title: 'Score details',
      summary: 'Score overview',
      scoreType: 'Score type',
      score: 'Score',
      maxScore: 'Max score',
      weight: 'Weight',
      grade: 'Grade',
      examDate: 'Exam date',
      remarks: 'Remarks',
      enrollment: 'Enrollment',
      enrollmentId: 'Enrollment ID',
      student: 'Student',
      studentId: 'Student ID',
      classSubjectId: 'Class-subject ID',
      notFound: 'Score not found'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('app_language') || 'vi');

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language === 'vi' ? 'vi' : 'en';
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language]
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
